[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
networking = { path = "../crates/networking" }
renet = "0.0.14"
anyhow = "1.0.77"
ctrlc = "3.4.2"